# Generated by Django 3.2.8 on 2022-02-15 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='reocrd_id',
            field=models.IntegerField(null=True, verbose_name='记录id'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='borrow_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 15, 18, 55, 14, 986310), verbose_name='借出时间'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='return_ddl',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 15, 18, 55, 14, 986329), verbose_name='归还期限'),
        ),
    ]
