# Generated by Django 3.2.8 on 2022-02-15 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220215_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='reocrd_id',
            new_name='record_id',
        ),
        migrations.AlterField(
            model_name='borrow',
            name='borrow_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 15, 19, 25, 27, 690314), verbose_name='借出时间'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='return_ddl',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 15, 19, 25, 27, 690334), verbose_name='归还期限'),
        ),
    ]
